# Generated by Django 3.1.6 on 2021-02-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210221_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], max_length=20, null=True),
        ),
    ]
